theme: jekyll-theme-cayman
title: Visually-Grounded Interaction and Language (ViGIL)
description: "NIPS 2017 Workshop, Long Beach, California, USA"
google_analytics: UA-106603221-1

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
