theme: jekyll-theme-cayman
title: Visually-Grounded Interaction and Learning
description: "NIPS 2017 Workshop, Long Beach, California, USA<br>
  Friday, December 8th, 08:00 AM — 06:30 PM"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
